<a href="https://colab.research.google.com/github/pallavibekal/CodeRepository/blob/main/Linear_Algebra_and_Calculus_Pallavi_M0_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Problem Statement

 The task is to advise a petroleum company on how to meet the demands of their customers for motor oil, diesel oil and gasoline.

## Objectives

At the end of the experiment, we will be able to

* create arrays and matrices in python
* understand the concepts of linear equations
* solve the system of linear equations

### Data

From a barrel of crude oil, in one day, factory $A$ can produce 
* 20 gallons of motor oil, 
* 10 gallons of diesel oil, and 
* 5 gallons of gasoline 

Similarly, factory $B$ can produce 
* 4 gallons of motor oil, 
* 14 gallons of diesel oil, and 
* 5 gallons of gasoline
 
while factory $C$ can produce 
* 4 gallons of motor oil,
* 5 gallons of diesel oil, and 
* 12 gallons of gasoline 

There is also waste in the form of paraffin, among other things. Factory $A$ has 3 gallons of paraffin to dispose of per barrel of crude, factory $B$ 5 gallons, and factory $C$ 2 gallons.

### Create an array 

Create an array of size 2x3 with arbitrary values.

In [ ]:

import numpy as np
import scipy.linalg as la
a = np.random.randint(5, size=(2,3))
print(a)

[[7 2 7]
 [7 7 6]]


### Create the system of Linear Equation

Suppose the current daily demand from distributors is 6600 gallons of motor oil, 5100 gallons of diesel oil and 3100 of gasoline.

Set up the system of equations which describes the above situation. Please include the units as well.

Let the number of barrels used by factory $A$, $B$ and $C$ are $x$, $y$ and $z$ respectively.

Then the system of linear equations will be

$$Motor\ oil:\ \ \ 20x + 4y + 4z = 6600$$

$$Diesel\ oil:\ \ \ 10x + 14y + 5z = 5100$$

$$Gasoline:\ \ \ 5x + 5y + 12z = 3100$$

### Solve the system of Linear Equation

How many barrels of crude oil each plant should get in order to meet the demand as a group. Remember that we can only provide each plant with an integral number of barrels.

In [ ]:

coefficients_data = [[20, 4, 4], [10, 14, 5], [5, 5, 12]]
coefficients = np.array(coefficients_data)
coefficients

Check determinant is non-zero

In [ ]:
np.linalg.det(coefficients)

2400.0000000000005

In [ ]:
terms_data = [6600, 5100, 3100]
terms = np.array(terms_data)
terms

array([6600, 5100, 3100])

In [ ]:
solutions = np.array(np.ceil(np.linalg.solve(coefficients, terms)), dtype=np.int32)
solutions

array([288, 129,  85], dtype=int32)

Suppose the total demand for all products **doubled**. What would the solution now be? How does it compare to the original solution? Why, mathematically, should this have been expected?

In [ ]:
# YOUR CODE HERE
double_terms = 2 * terms
double_terms

array([13200, 10200,  6200])

In [ ]:
double_terms_solutions = np.array(np.ceil(np.linalg.solve(coefficients, double_terms)), dtype=np.int32)
double_terms_solutions

array([575, 258, 170], dtype=int32)

Suppose that the company acquires another group of distributors and that the daily demand of this group is 2000 gallons of motor oil, 4000 gallons of gasoline, and 4000 gallons of diesel oil. How would you set up production of just this supply? Are there any options (more than one way)?

In [ ]:

group2_terms = np.array([2000, 4000, 4000])
group2_solutions = np.ceil(np.linalg.solve(coefficients, group2_terms))
group2_solutions

array([ 13., 188., 250.])

Next, calculate the needs of each factory (in barrels of crude, as usual) to meet the total demand of both groups of distributors. When you have done this, compare your answer to results already obtained. What mathematical conclusion can you draw?

In [ ]:

combined_terms = group2_terms + terms
combined_solutions = np.ceil(np.linalg.solve(coefficients, combined_terms))
combined_solutions

array([300., 317., 335.])

combine_solution = solutions + group2_solutions

In [ ]:
solutions

### Sensitivity and Robustness

In real life applications, constants are rarely ever exactly equal to their stated value; certain amounts of uncertainty are always present. This is part of the reason for the science of statistics. In the above model, the daily productions for the plants would be averages over a period of time. Explore what effect small changes in the parameters have on the output.

To do this, pick any 3 coefficients, one at a time, and increase or decrease them by 3%. For each case , note what effect this has on the solution, as a percentage change. Can you draw any overall conclusion?

In [ ]:


a = np.array([[20, 4, 4],
              [10, 14, 5],
              [5, 5, 12]])
b = np.array([6600, 5100, 3100])
X = np.linalg.solve(a, b)
x = X[0]
y = X[1]
z = X[2]
#print(x,y,z)
A = 20*x + 10*x + 5*x
B = 4*y + 14*y + 5*y
C = 4*z + 5*z + 12*z

print("# Original Prod output with specific plants")
print("A :", A ,"\nB : ", B ,"\nC : ", C )

# Original Prod output with specific plants
A : 10053.75 
B :  2961.25 
C :  1785.0


In [ ]:
# Increasing x coefficient by 3%
a1 = np.array([[20 + 20*0.03, 4, 4],
              [10 + 10*0.03, 14, 5],
              [5 + 5 * 0.03, 5, 12]])
b1 = np.array([6600, 5100, 3100])

X1 = np.linalg.solve(a1, b1)
print(X1)
A11 = 20*X1[0] + 10*X1[0] + 5*X[0]
B11 = 4*X1[1] + 14*X1[1] + 5*X1[1]
C11 = 4*X1[2] + 5*X1[2] + 12*X1[2]
print("# Increasing x coefficient by 3%, Prod output with specific plants")
print("A11 :", A11 ,"\nB11 : ", B11 ,"\nC11 : ", C11 )




[278.88349515 128.75        85.        ]
# Increasing x coefficient by 3%, Prod output with specific plants
A11 : 9802.754854368932 
B11 :  2961.25 
C11 :  1785.0


In [ ]:
# Increasing y coefficient
a2 = np.array([[20 , 4 + 4*0.03, 4],
              [10 , 14 + 14*0.03, 5],
              [5 , 5 + 5*0.03, 12]])
b2 = np.array([6600, 5100, 3100])

X2 = np.linalg.solve(a2, b2)
#print(X2)
A12 = 20*X2[0] + 10*X2[0] + 5*X2[0]
B12 = 4*X2[1] + 14*X2[1] + 5*X2[1]
C12 = 4*X2[2] + 5*X2[2] + 12*X2[2]
print("# # Increasing y coefficient, Prod output with specific plants")
print("A12 :", A12 ,"\nB12 : ", B12 ,"\nC12 : ", C12 )

# # Increasing y coefficient, Prod output with specific plants
A12 : 10053.75 
B12 :  2875.0 
C12 :  1784.9999999999995


In [ ]:
print(X, X1)
(X - X1) / X1

[287.25 128.75  85.  ] [278.88349515 128.75        85.        ]


array([0.03, 0.  , 0.  ])

In [ ]:
# Increasing z coefficient
a3 = np.array([[20 , 4 + 4, 4 + 4*0.03],
              [10 , 14 + 14, 5 + 5*0.03],
              [5 , 5 + 5, 12 + 12*0.03]])
b3 = np.array([6600, 5100, 3100])

X3 = np.linalg.solve(a3, b3)
#print(X2)
A13 = 20*X3[0] + 10*X3[0] + 5*X3[0]
B13 = 4*X3[1] + 14*X3[1] + 5*X3[1]
C13 = 4*X3[2] + 5*X3[2] + 12*X3[2]
print("# # Increasing z coefficient, Prod output with specific plants")
print("A13 :", A13 ,"\nB13 : ", B13 ,"\nC13 : ", C13 )

# # Increasing z coefficient, Prod output with specific plants
A13 : 10053.75 
B13 :  1480.625 
C13 :  1733.0097087378645


In [ ]:
(X - X3)/X3

array([0.  , 1.  , 0.03])

In [ ]:
print("# Original Prod output with specific plants")
print("A :", A ,"\nB : ", B ,"\nC : ", C )

print("# After increasing x by  3% with coefficients, Prod output with specific plants")
print("A11 :", A11 ,"\nB11 : ", B11 ,"\nC11 : ", C11 )

print("# After increasing y by 3% with coefficients, Prod output with specific plants")
print("A12 :", A12 ,"\nB12 : ", B12 ,"\nC12 : ", C12 )

print("# After increasing z by 3% with coefficients, Prod output with specific plants")
print("A13 :", A13 ,"\nB13 : ", B13 ,"\nC13 : ", C13 )

# Original Prod output with specific plants
A : 10053.75 
B :  2961.25 
C :  1785.0
# After increasing x by  3% with coefficients, Prod output with specific plants
A11 : 9802.754854368932 
B11 :  2961.25 
C11 :  1785.0
# After increasing y by 3% with coefficients, Prod output with specific plants
A12 : 10053.75 
B12 :  2875.0 
C12 :  1784.9999999999995
# After increasing z by 3% with coefficients, Prod output with specific plants
A13 : 10053.75 
B13 :  1480.625 
C13 :  1733.0097087378645



3 % increase with coefficient Y, increase with overall production, increase with Z coefficient decrease with overall production.

### A Plant Off-Line

Suppose factory $C$ is shut down by the EPA (Environmental Protection Agency) temporarily for excessive emissions into the atmosphere. If your demand is as it was originally (6600, 5100, 3100), what would you now say about the companies ability to meet it? What do you recommend they schedule for production now?

In [ ]:

# My equations now, with C shut off will be 
#         20x +  4y = 6600
#         10x + 14y = 5100
#          5x +  5y = 3100

# We now have an overdetermined system - no of equations > no.of unknowns. There is no single solution. Hence we use the numpy linalg-lstsq to get an approximate solution. 
import numpy as np
AP = np.array([[20,4],[10,14],[5,5]])
bp = np.array([6600,5100,3100])
xp = np.linalg.lstsq(AP,bp,rcond=None)
xp1, xp2 = np.ceil(xp[0])
print('This is an overdetermined system, therefore there is no single solution')
print('Least Square Solution for the overdetermined system is - ',xp1,xp2)




This is an overdetermined system, therefore there is no single solution
Least Square Solution for the overdetermined system is -  300.0 169.0


### Buying another plant

This situation has caused enough concern that the CEO is considering buying another plant, identical to the third, and using it permanently. Assuming that all 4 plants are on line, what production do you recommend to meet the current demand (5000, 8500, 10000)? In general, what can you say about any increased flexibility that the 4th plant might provide?

Let the number of barrels used by factory $A$, $B$, $C$ and $D$ are $x$, $y$, $z$ and $w$ respectively.

Then the system of linear equations will be

$$20x + 4y + 4z + 4w = 5000$$

$$10x + 14y + 5z + 5w = 8500$$

$$5x + 5y + 12z + 12w = 10000$$

The above system of linear equation has fewer equations than variables, hence it is *underdetermined* and cannot have a unique solution. In this case, there are either infinitely many solutions or no exact solution. We can solve it by keeping $w$ as constant and using [rref](http://linear.ups.edu/html/section-RREF.html) form to solve the system of linear equation.

To know about rref implementation in python refer [here](https://docs.sympy.org/latest/tutorial/matrices.html#rref).

In [ ]:
import sympy as sy

# create symbol 'w'
w = sy.Symbol("w")            
A_aug = sy.Matrix([[20, 4, 4, 5000-4*w], 
                   [10, 14, 5, 8500-5*w], 
                   [5, 5, 12, 10000-12*w]])
# show rref form
A_aug.rref()                  

(Matrix([
 [1, 0, 0,   195/4],
 [0, 1, 0,  1325/4],
 [0, 0, 1, 675 - w]]),
 (0, 1, 2))

From the above result, it can be seen that 4th plant will share the number of barrels required by the 3rd plant only, while the requirement of 1st and 2nd plant will remain unaffected.

### Calculate the amount of Paraffin supplied

The company has just found a candle company that will buy its paraffin. Under the current conditions (i.e, after buying another plant) for demand (5000, 8500, 10000), how much can be supplied to them per day?

According to the problem statement, factory $A$ has 3 gallons of paraffin to dispose of per barrel of crude oil, factory $B$ 5 gallons, and factory $C$ 2 gallons.

In [ ]:

supply = (195/4) * 3 + (1325/4) * 5 + (675) * 2
print("Paraffin supply = ",supply)

Paraffin supply =  3152.5


### Selling the first plant

The management is also considering selling the first plant due to aging equipment and high workman's compensation costs for the state it is located in. They would like to know what this would do to their production capability. Specifically, they would like an example of a demand they could not meet with only plants 2 and 3, and also what effect having plant 4 has (recall it is identical to plant 3). They would also like an example of a demand that they could meet with just plants 2 and 3. Any general statements you could make here would be helpful.

Let the number of barrels used by factory $B$, $C$ and $D$ are $y$, $z$ and $w$ respectively.

When considering only plants 2 and 3, and demand (5000, 8500, 10000) then we have

$$4y + 4z = 5000$$

$$14y + 5z = 8500$$

$$5y + 12z = 10000$$

In [ ]:

import sympy as sy

#Solving first and second equations
A_S = np.array([[4,4],[14,5],[5,12]])
B_S = np.array([5000,8500,10000]).reshape(3,1)

A_S1 = np.array([[4,4],[14,5]])
B_S1 = np.array([5000,8500]).reshape(2,1)

A_S1_INV = la.inv(A_S1)
print(A_S1_INV @ B_S1)

#Solving second and third equations
A_S2 = np.array([[14,5],[5,12]])
B_S2 = np.array([8500,10000]).reshape(2,1)

A_S2_INV = la.inv(A_S2)

print(A_S2_INV @ B_S2)

#Solving first and last equations

A_S3 = np.array([[4,4],[5,12]])
B_S3 = np.array([5000,10000]).reshape(2,1)

A_S3_INV = la.inv(A_S3)

print(A_S3_INV @ B_S3)


# NO CONSISTENT SOLTUION EXISTS


[[ 250.]
 [1000.]]
[[363.63636364]
 [681.81818182]]
[[714.28571429]
 [535.71428571]]


Taking 4th plant into consideration.
Let the number of barrels used by factory $B$, $C$ and $D$ are $y$, $z$ and $w$ respectively.

Then for demand (5000, 8500, 10000) the system of linear equations will be

$$4y + 4z + 4w = 5000$$

$$14y + 5z + 5w = 8500$$

$$5y + 12z + 12w = 10000$$

Solve it using rref form.

In [ ]:

# 
#D_S = np.array([[4,4,4],[14,5,5],[5,12,12]]) 

# create symbol 'w'
w = sy.Symbol("w")            
A_aug = sy.Matrix([[4, 4, 4,  5000], 
                   [14, 5,5, 8500], 
                   [5, 12,12, 10000]])
# show rref form
A_aug.rref()

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 1, 0],
 [0, 0, 0, 1]]), (0, 1, 3))

Now, changing demand to (6600, 5100, 3100) and solving the system of equation using rref form.

In [ ]:

# create symbol 'w'
w = sy.Symbol("w")            
A_aug2 = sy.Matrix([[4, 4,4,  6600], 
                   [14, 5,5, 5100], 
                   [5, 12,12, 3100]])
# show rref form
A_aug2.rref()

The equations do not provide a solution for both the demand values, using `Rref` form. Our understanding here is that plant C and plant D have the same coefficients/rates so the row reduced echelon is not providing us a feasible solution


### Set rates for Products

Company wants to set the rates of motor oil, diesel oil, and gasoline. For this purpose they have few suggestions given as follows: 

* 100, 66, 102 Rupees per gallon,

* 104, 64, 100 Rupees per gallon,

* 102, 68, 98 Rupees per gallon, and

* 96, 68, 100 Rupees per gallon 

for motor oil, diesel oil, and gasoline respectively.

Using matrix multiplication, find the rates which results in maximum total price.

Let $M$ denotes the matrix such that rows represents different plants (A, B and C), columns represents different products (motor oil, diesel oil and gasoline) and each value represents production of that product from one barrel of crude oil for that plant.

$$M = \begin{bmatrix}
20 & 10 & 5 \\ 
4 & 14 & 5  \\ 
 4 & 5 & 12  
\end{bmatrix}$$

Also, $R$ is a matrix having different rates as its columns.

$$R = \begin{bmatrix}
100 & 104 & 102 & 96 \\ 
66 & 64 & 68 & 68  \\ 
102 & 100 & 98 & 100  
\end{bmatrix}$$

Loading data for the M array

In [ ]:

m_data = [[20, 10, 5], [4, 14, 5], [4, 5, 12]]
m = np.array(m_data)
m

array([[20, 10,  5],
       [ 4, 14,  5],
       [ 4,  5, 12]])

Loading data for the R array

In [ ]:
r_data = [[100, 104, 102, 96], [66, 64, 68, 68], [102, 100, 98, 100]]
r = np.array(r_data)
r

array([[100, 104, 102,  96],
       [ 66,  64,  68,  68],
       [102, 100,  98, 100]])

Dot product of M and R will give us total price across plants (i.e. rows) and scenarios (ie. columns)

In [ ]:
total_price = m.dot(r)
total_price

array([[3170, 3220, 3210, 3100],
       [1834, 1812, 1850, 1836],
       [1954, 1936, 1924, 1924]])

We calculate the sum of prices across plants, i.e. by columns of total_price

In [ ]:
total_price_across_plants = np.array(total_price.sum(axis=0), dtype = np.int32)
total_price_across_plants

array([6958, 6968, 6984, 6860], dtype=int32)

Lets find the max of all the total prices and which scenario (i.e. its column index)

In [ ]:
max_total_price = np.max(total_price_across_plants)
max_total_price

6984

In [ ]:
scenario = np.where(total_price_across_plants == max_total_price)
print("The scenario which gives maximum pricing : {}".format(scenario[0][0] + 1))

The scenario which gives maximum pricing : 2


### Marginal Cost

The total cost $C(x)$ in Rupees, associated with the production of $x$ gallons of gasoline is given by 

$$C(x) = 0.005 x^3 – 0.02 x^2 + 30x + 5000$$

Find the marginal cost when $22$ gallons are produced, where, marginal cost means the instantaneous rate of change of total cost at any level of output.

In [ ]:

def f(x):
  return (0.005*x**3) - (0.02*x**2) + 30*x + 5000

from scipy.misc import derivative

print('The marginal cost is ',derivative(f,22).round(4))


The marginal cost is  36.385


### Marginal Revenue

The total revenue in Rupees received from the sale of $x$ gallons of a motor oil is given by $$R(x) = 3x^2 + 36x + 5.$$ 

Find the marginal revenue, when $x = 28$, where, marginal revenue means the rate of change of total revenue with respect to the number of items sold at an instant.

In [ ]:

from sympy import Symbol, diff
  
x = Symbol('x')
R = 3 * x**2 + 36 * x + 5
print("Revenue function : {} ".format(R))
   
MR = diff(R, x)  
      
print("Marginal Revenue function : {} ".format(MR))

# Marginal revenue when x = 28
print("Marginal revenue is : {}".format(MR.evalf(subs = {x: 28})))

Revenue function : 3*x**2 + 36*x + 5 
Marginal Revenue function : 6*x + 36 
Marginal revenue is : 204.000000000000


### Pour crude oil in tank

In a cylindrical tank of radius 10 meter, crude oil is being poured at the rate of 314 cubic meter per hour. Then find

* the rate at which the height of the tank is increasing, and
* the height of crude oil in tank after 2 hours.

In [ ]:

r = 10
dvdt = 314
pi = 3.14
#dV/dr = 2πrh
dhdt = dvdt/(pi*r*r)

print("Rate of Height the tank increasing in 1hr : " , dhdt)
print("Rate of Height the tank increasing in 2hr : " , 2*dhdt)

Rate of Height the tank increasing in 1hr :  1.0
Rate of Height the tank increasing in 2hr :  2.0
